// Delay/abort only the detail image: deterministic cold-load and failure fixtures.
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('fs');
const out=process.env.OUTPUT_DIR||'outputs/image-layout';fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch({channel:'chrome'}),results=[];
for(const width of [1280,390])for(const id of ['layered-paper','duotone-print','colored-pencil-diary'])for(const fail of [false,true]){const c=await b.newContext({viewport:{width,height:800}}),p=await c.newPage();await p.goto(process.env.GALLERY_URL||'http://127.0.0.1:4347/dist/');const data=await (await c.request.get(new URL('styles.json',p.url()).href)).json(),s=data.find(s=>s.id===id);await p.getByRole('button',{name:`查看${s.name}详情`,exact:true}).waitFor();let release,requested;const requestSeen=new Promise(r=>requested=r),gate=new Promise(r=>release=r);await p.route(new URL(s.image,p.url()).href,async route=>{requested();await gate;fail?await route.abort():await route.continue();});const opener=p.getByRole('button',{name:`查看${s.name}详情`,exact:true});await opener.scrollIntoViewIfNeeded();const original=await p.evaluate(()=>scrollY);await opener.click();await requestSeen;
const measure=()=>p.evaluate(()=>Object.fromEntries(['#detail .detail-header','#closeDetail','#detailBody img','.detail-summary','#detail .detail-footer'].map(sel=>{const r=document.querySelector(sel).getBoundingClientRect();return [sel,{x:r.x,y:r.y,width:r.width,height:r.height}]})));
const before=await measure();await p.screenshot({path:`${out}/${width}-${id}-${fail?'fail':'load'}-before.png`});release();if(fail)await p.waitForFunction(()=>{const i=document.querySelector('#detailBody img');return i.complete&&i.naturalWidth===0});else await p.locator('#detailBody img').evaluate(i=>i.decode());await p.waitForTimeout(100);const after=await measure();await p.screenshot({path:`${out}/${width}-${id}-${fail?'fail':'load'}-after.png`});const delta=Object.fromEntries(Object.keys(before).map(k=>[k,Object.fromEntries(Object.keys(before[k]).map(v=>[v,after[k][v]-before[k][v]]))]));results.push({width,id,fail,before,after,delta});console.log(width,id,fail?'failed image':'loaded image',JSON.stringify(delta));
if(!process.env.BASELINE){for(const value of Object.values(delta))for(const n of Object.values(value))assert(Math.abs(n)<=1,'image load shifted layout');if(fail)assert(await p.getByText('样图暂时无法加载，请稍后重试。',{exact:true}).isVisible());else {const ratio=await p.locator('#detailBody img').evaluate(i=>({w:i.width,h:i.height,nw:i.naturalWidth,nh:i.naturalHeight,fit:getComputedStyle(i).objectFit}));assert.equal(ratio.fit,'contain');assert.equal(ratio.nw,s.image_width);assert.equal(ratio.nh,s.image_height);}const closeBefore=await p.locator('#closeDetail').boundingBox();await p.locator('#detailBody').hover();await p.mouse.wheel(0,3500);await p.waitForTimeout(100);assert.deepEqual(await p.locator('#closeDetail').boundingBox(),closeBefore);assert.equal(await p.evaluate(()=>document.body.style.position),'fixed');assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.locator('#closeDetail').click();assert.equal(await p.evaluate(()=>scrollY),original);assert(await opener.evaluate(e=>document.activeElement===e));}
await c.close();}await b.close();fs.writeFileSync(`${out}/report.json`,JSON.stringify({at:new Date().toISOString(),baseline:Boolean(process.env.BASELINE),results},null,2));})().catch(e=>{console.error(e);process.exit(1)});
