// Run with Playwright available in NODE_PATH and GALLERY_URL pointing to a static gallery.
const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({channel:'chrome'});for(const width of [1280,390]){const p=await b.newPage({viewport:{width,height:900}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(process.env.GALLERY_URL||'http://127.0.0.1:4339/');const card=()=>p.locator('#cards .card').first();await card().waitFor();assert.equal(await p.locator('#pageSizeBottom').count(),0);
for(const target of ['img','h2']){await card().locator(target).click();await p.locator('#detail[open]').waitFor();await p.click('#closeDetail');}
await card().click({position:{x:5,y:5}});await p.locator('#detail[open]').waitFor();await p.keyboard.press('Escape');
await card().getByRole('button',{name:/^查看.+详情$/}).focus();await p.keyboard.press('Enter');await p.locator('#detail[open]').waitFor();await p.keyboard.press('Escape');
await card().locator('.card-title').press('Space');await p.locator('#detail[open]').waitFor();await p.keyboard.press('Escape');assert(await card().locator('.card-title').evaluate(e=>e===document.activeElement));
for(const target of ['label','.badge']){await card().locator(target).click();assert.equal(await p.locator('#detail[open]').count(),0);}
await card().getByRole('button',{name:/^收藏/}).click();assert.equal(await p.locator('#detail[open]').count(),0);
await card().getByRole('button',{name:/查看家族/}).click();assert.equal(await p.locator('#detail[open]').count(),0);
await card().locator('h2').evaluate(el=>{const range=document.createRange();range.selectNodeContents(el);getSelection().removeAllRanges();getSelection().addRange(range);});await card().locator('h2').dispatchEvent('click');assert.equal(await p.locator('#detail[open]').count(),0);await p.evaluate(()=>getSelection().removeAllRanges());
const text=card().locator('p').first();await text.scrollIntoViewIfNeeded();const rect=await text.boundingBox();await p.mouse.move(rect.x+3,rect.y+10);await p.mouse.down();await p.mouse.move(rect.x+130,rect.y+10,{steps:12});await p.mouse.up();assert(await p.evaluate(()=>getSelection().toString().length>0));assert.equal(await p.locator('#detail[open]').count(),0);await p.evaluate(()=>getSelection().removeAllRanges());
await card().getByRole('button',{name:/^选择/}).click();await p.locator('#brief:not([hidden])').waitFor();assert.equal(await p.locator('#detail[open]').count(),0);await p.click('#backGallery');
if(width===390)await p.click('#mobileFilters');await p.selectOption('#family','all');await p.selectOption('#browseMode','all');await p.selectOption('#pageSize','50');await p.click('#nextPage');assert.match(await p.locator('#pageInfo').textContent(),/第 2/);for(const value of ['100','150','200','all','50']){await p.selectOption('#pageSize',value);assert.match(await p.locator('#pageInfo').textContent(),/第 1/);assert.equal(await p.locator('#cards .card').count(),value==='all'?308:Number(value));}
assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);await p.screenshot({path:`outputs/demand-check/cards-${width}.png`});await p.close();console.log(width,'card interactions and pagination passed');}await b.close()})().catch(e=>{console.error(e);process.exit(1)});
